chore(dns): improve dns resolution for build-image workflow

diff --git a/.github/workflows/build-image.yml b/.github/workflows/build-image.yml
--- a/.github/workflows/build-image.yml
+++ b/.github/workflows/build-image.yml
@@ -81,22 +81,43 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
+      - name: Check DNS Resolution for Vault
+        if: inputs.vault_enabled
+        run: |
+          extract_domain() {
+            echo "$1" | awk -F[/:] '{print $4}'
+          }
+
+          VAULT_DOMAIN=$(extract_domain "${{ env.VAULT_ADDR }}")
+
+          for i in {1..100}; do
+            if nslookup $VAULT_DOMAIN; then
+              echo "DNS resolution successful"
+              break
+            else
+              echo "DNS resolution failed, retrying in 10 seconds..."
+              sleep 15
+            fi
+          done
+          # Exit with error if DNS resolution fails after retries
+          if ! nslookup $VAULT_DOMAIN; then
+            echo "DNS resolution failed after multiple attempts"
+            exit 1
+          fi
+        shell: bash
+
       - name: Import Secrets
-        uses: Wandalen/wretry.action@v3
         if: inputs.vault_enabled
         id: secrets
+        uses: hashicorp/vault-action@v3
         with:
-          action: hashicorp/vault-action@v3
-          attempt_limit: 15
-          attempt_delay: 500
-          with: |
-            url: ${{ env.VAULT_ADDR }}
-            role: ${{ env.VAULT_GITHUB_ACTIONS_ROLE }}
-            method: jwt
-            path: "github-actions"
-            exportToken: true
-            secrets: |
-              github/token/read_repositories token | GH_ORG_READ_REPO_TOKEN ;
+          url: ${{ env.VAULT_ADDR }}
+          role: ${{ env.VAULT_GITHUB_ACTIONS_ROLE }}
+          method: jwt
+          path: "github-actions"
+          exportToken: true
+          secrets: |
+            github/token/read_repositories token | GH_ORG_READ_REPO_TOKEN ;
 
       - name: Configure AWS Credentials
         id: aws
